
services:

  db:
    container_name: systolic_db
    image: postgres:latest
    restart: unless-stopped
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - 5432:5432
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: systolic
      POSTGRES_DB: systolic_db
    volumes:
      - pgdata:/var/lib/postgresql/data

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  pgdata: